In [2]:
import pandas as pd
import numpy as np

# Read the SAS7BDAT file
df = pd.read_sas('pums.sas7bdat')

# Display the data

In [4]:
df.describe()

,RG,TABWGT,EMPLOYMENT_NOISY,PAYROLL_NOISY,RECEIPTS_NOISY,PCT1,PCT2,PCT3,PCT4
count,2.165680e+06,2.165680e+06,2.165680e+06,2.165680e+06,2.165680e+06,2.165680e+06,2.165679e+06,2.165678e+06,2.165677e+06
mean,4.314542e+00,1.218658e+01,1.406755e+01,5.225482e+02,2.897614e+03,8.034336e+01,1.662174e+01,2.188383e+00,8.465274e-01
std,3.404692e+00,1.109563e+01,1.512690e+02,4.991237e+03,3.766236e+04,2.532962e+01,2.182504e+01,7.073099e+00,4.035502e+00
min,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.000000e+00,2.162000e+00,0.000000e+00,0.000000e+00,1.000000e+01,5.000000e+01,0.000000e+00,0.000000e+00,0.000000e+00
50%,4.000000e+00,7.502000e+00,0.000000e+00,0.000000e+00,9.000000e+01,1.000000e+02,0.000000e+00,0.000000e+00,0.000000e+00
75%,7.000000e+00,1.998500e+01,5.000000e+00,1.200000e+02,6.100000e+02,1.000000e+02,4.900000e+01,0.000000e+00,0.000000e+00
max,1.000000e+01,3.500000e+01,9.100000e+04,2.400000e+06,1.400000e+07,1.000000e+02,1.000000e+02,1.000000e+02,1.000000e+02

In [5]:
df.head()

,FIPST,SECTOR,N07_EMPLOYER,RG,TABWGT,EMPLOYMENT_NOISY,PAYROLL_NOISY,RECEIPTS_NOISY,PCT1,PCT2,...,NOBUSCRED,NOPERSCRED,STARTANOTHER,SOLDBUS,CEASEOTHER,CEASENR,CEASENA,HUSBWIFE,FAMILYBUS,NUMOWNERS
0,b'23',b'51',b'E',3.0,5.4,9.0,140.0,360.0,74.0,21.0,...,b'0',b'0',b'0',b'0',b'0',b'2',b'1',b'2',b'1',b'3'
1,b'23',b'44',b'E',0.0,1.0,74.0,2100.0,20000.0,100.0,0.0,...,b'0',b'0',b'0',b'0',b'0',b'2',b'1',b'0',b'0',b'0'
2,b'23',b'55',b'E',5.0,1.0,2.0,40.0,230.0,27.0,27.0,...,b'0',b'0',b'0',b'0',b'0',b'2',b'1',b'4',b'1',b'5'
3,b'23',b'54',b'E',0.0,1.0,34.0,1700.0,6900.0,31.0,31.0,...,b'0',b'0',b'0',b'0',b'0',b'2',b'1',b'4',b'2',b'6'
4,b'23',b'51',b'E',0.0,1.0,120.0,3700.0,9100.0,34.0,33.0,...,b'0',b'0',b'0',b'0',b'0',b'2',b'1',b'4',b'2',b'3'